
const C=window.PROPERTY_CONFIG,L=window.URBAN_LOCALES;let lang=localStorage.getItem('usg-lang')||'es';
const navOrder=['home','homeinfo','parking','restaurants','discover','events','services','checkout'];
const beaches=[
 {name:'Samil',icon:'🏖️',km:'6,4',time:'14',tip:'family',q:'Praia de Samil Vigo'},
 {name:'O Vao',icon:'🌊',km:'8,1',time:'16',tip:'sand',q:'Praia do Vao Vigo'},
 {name:'Canido',icon:'⚓',km:'8,0',time:'15',tip:'food',q:'Praia de Canido Vigo'},
 {name:'Monte do Castro',icon:'🌅',km:'2,1',time:'8',tip:'sunset',q:'Monte do Castro Vigo'},
 {name:'Monte da Guía',icon:'🔭',km:'5,0',time:'13',tip:'view',q:'Monte da Guia Vigo'},
 {name:'Paseo de Bouzas',icon:'🚶',km:'3,8',time:'11',tip:'walk',q:'Paseo de Bouzas Vigo'}];
const events=[
 {name:'Abraham Mateo · Castrelos',date:'7 AGO 2026',icon:'🎤',place:'Auditorio de Castrelos',url:'https://turismodevigo.org/es/actualidad/un-concierto-al-aire-libre-en-castrelos'},
 {name:'Ópera Nabucco · Castrelos',date:'9 AGO 2026',icon:'🎭',place:'Auditorio de Castrelos',url:'https://turismodevigo.org/es/actualidad/un-concierto-al-aire-libre-en-castrelos'},
 {name:'The Corrs · Castrelos',date:'11 AGO 2026',icon:'🎶',place:'Auditorio de Castrelos',url:'https://turismodevigo.org/es/actualidad/un-concierto-al-aire-libre-en-castrelos'},
 {name:'Viva Suecia · Castrelos',date:'14 AGO 2026',icon:'🎸',place:'Auditorio de Castrelos',url:'https://turismodevigo.org/es/actualidad/un-concierto-al-aire-libre-en-castrelos'},
 {name:'Iván Ferreiro · Castrelos',date:'15 AGO 2026',icon:'🎙️',place:'Auditorio de Castrelos',url:'https://turismodevigo.org/es/actualidad/un-concierto-al-aire-libre-en-castrelos'},
 {name:'Agenda oficial de Vigo',date:'ACTUALIZADA',icon:'📅',place:'Concello de Vigo',url:'https://hoxe.vigo.org/?lang=cas'}
];
const services=[['💊','pharmacy','farmacia abierta'],['🏥','hospital','urgencias hospital'],['🛒','supermarket','supermercado'],['🥖','bakery','panaderia'],['🍰','pastry','pasteleria'],['🧺','laundry','lavanderia autoservicio'],['🚕','taxi','taxi'],['🚌','transport','parada autobus'],['🏧','atm','cajero automatico'],['⛽','fuel','gasolinera']];
const serviceNames={es:{pharmacy:'Farmacia abierta',hospital:'Urgencias y hospital',supermarket:'Supermercados',bakery:'Panaderías',pastry:'Pastelerías',laundry:'Lavanderías',taxi:'Taxi',transport:'Transporte público',atm:'Cajeros',fuel:'Gasolineras'},en:{pharmacy:'Open pharmacy',hospital:'Emergency care and hospital',supermarket:'Supermarkets',bakery:'Bakeries',pastry:'Pastry shops',laundry:'Laundries',taxi:'Taxi',transport:'Public transport',atm:'ATMs',fuel:'Fuel stations'}};
function t(k){return k.split('.').reduce((o,x)=>o?.[x],L[lang]) ?? k}
function link(q){return `https://www.google.com/maps/search/?api=1&query=${encodeURIComponent(q+' cerca de '+C.address)}`}
function nav(){let html=navOrder.map(x=>`<a href="#${x}" data-r="${x}">${t('nav.'+x)}</a>`).join('');desktopNav.innerHTML=html;drawer.innerHTML=html;}
function layout(title,lead,body,ey='URBAN STAY GUIDE'){return `<section class="section"><div class="section-head"><span class="eyebrow">${ey}</span><h2>${title}</h2><p class="lead">${lead}</p></div>${body}</section>`}
function home(){
 const upcoming=events.slice(0,4).map(e=>`<a class="event-mini" target="_blank" rel="noopener" href="${e.url}"><span>${e.icon}</span><div><small>${e.date}</small><strong>${e.name}</strong><em>${e.place}</em></div></a>`).join('');
 return `<section class="hero"><img src="${C.hero}"><div class="hero-content"><span class="eyebrow">URBAN STAY GUIDE · VIGO</span><img src="${C.logo}"><h1>${t('welcome')}</h1><p>${t('subtitle')}</p><a class="btn gold" href="#restaurants">🍽️ ${t('explore')}</a></div></section>${layout(C.name,t('homeModulesLead'),`<div class="fact-grid"><div><span>${t('checkin')}</span><strong>${C.checkin}</strong></div><div><span>${t('checkout')}</span><strong>${C.checkout}</strong></div><div><span>${t('languages')}</span><strong>7</strong></div><div><span>Vigo</span><strong>360°</strong></div></div><div class="grid four" style="margin-top:20px">${[['🚗','parking'],['🍽️','restaurants'],['🏖️','discover'],['🎉','events']].map(([i,r])=>`<a class="card module-card" href="#${r}"><div class="card-icon">${i}</div><h3>${t('nav.'+r)}</h3><p>${r==='parking'?t('parkingLead'):r==='restaurants'?t('restaurantsLead'):r==='discover'?t('beachesLead'):t('eventsLead')}</p></a>`).join('')}</div><div class="home-events"><div class="home-events-head"><div><span class="eyebrow">VIGO EN VIVO</span><h3>${t('eventsTitle')}</h3></div><a class="btn outline" href="#events">${t('fullAgenda')}</a></div><div class="event-mini-grid">${upcoming}</div></div>`,t('quick'))}`
}
function homeinfo(){
 let imgs=['assets/living.jpeg','assets/kitchen-living.jpeg','assets/room-green.jpeg','assets/bath-green.jpeg','assets/room-grey.jpeg','assets/bath-grey.jpeg','assets/room-neutral.jpeg','assets/room-check.jpeg'];
 return layout(t('homeinfoTitle'),t('homeinfoLead'),`<div class="fact-grid"><div><strong>${C.rooms}</strong><span>${t('rooms')}</span></div><div><strong>${C.baths}</strong><span>${t('baths')}</span></div><div><strong>${C.guests}</strong><span>${t('guests')}</span></div><div><strong>${C.checkout}</strong><span>${t('checkout')}</span></div></div><div class="gallery property-gallery" style="margin-top:20px">${imgs.map((x,i)=>`<figure><img src="${x}" loading="lazy" alt="Barcelona 80 Urban Stay · ${i+1}"></figure>`).join('')}</div><div class="card amenities-card" style="margin-top:20px"><div class="card-icon">🏡</div><h3>${t('homeinfoTitle')}</h3><p>${t('amenities')}</p></div>`,'URBAN STAY · '+C.short)
}
function parking(){
 const isB=C.propertyKey==='b';
 const zone1Streets=isB
  ? ['Av. da Gran Vía','Rúa do Carme','Rúa de Pi i Margall','Baixada á Ponte Nova','Rúa Zamora','Rúa Tarragona','Rúa Sevilla','Rúa Zaragoza']
  : ['Av. da Gran Vía','Rúa do Carme','Rúa Zamora','Rúa de Pi i Margall','Rúa Tarragona','Rúa Sevilla','Rúa Zaragoza','Baixada á Ponte Nova'];
 const zone2Streets=['Rúa de Barcelona','Camiño do Regueiro','Camiño de Rioboo','Rúa Conde','Rúa das Teixugueiras','Av. de Castrelos','Rúa Zaragoza','Rúa Sevilla'];
 const streetList=(items)=>items.map(x=>`<span class="street-chip">${x}</span>`).join('');
 const zoneMap=(n,items,variant)=>{
  const label=n===1?t('free1'):t('free2');
  const zonePath=variant===1?'M80 95 Q240 30 430 82 Q520 145 465 315 Q330 400 135 337 Q45 240 80 95Z':'M365 185 Q550 95 785 170 Q865 290 800 475 Q620 565 430 485 Q330 350 365 185Z';
  const homeX=variant===1?650:235, homeY=variant===1?390:390;
  const labels=variant===1
   ? [['Av. da Gran Vía',80,370,-4,22],['Rúa do Carme',135,175,-12,18],['Rúa de Pi i Margall',80,285,-5,17],['Baixada á Ponte Nova',500,120,82,17],['Rúa Zamora',335,105,78,17],['Rúa Tarragona',355,230,7,16],['Rúa Sevilla',430,285,5,16],['Rúa Zaragoza',460,335,5,16]]
   : [['Av. de Castrelos',420,505,-7,22],['Rúa de Barcelona',165,335,-4,18],['Camiño do Regueiro',450,420,-5,18],['Camiño de Rioboo',575,510,-5,17],['Rúa Conde',690,215,-10,17],['Rúa das Teixugueiras',590,135,7,16],['Rúa Zaragoza',305,280,5,16],['Rúa Sevilla',375,225,5,16]];
  const text=labels.map(x=>`<text x="${x[1]}" y="${x[2]}" transform="rotate(${x[3]} ${x[1]} ${x[2]})" font-size="${x[4]}">${x[0]}</text>`).join('');
  return `<article class="card parking-zone-card"><div class="parking-zone-head"><div><span class="eyebrow">SMART PARKING</span><h3>🟢 ${label}</h3><p>${items.join(' · ')}</p></div><span class="walk-badge">🚶 2–5 min</span></div><div class="parking-map premium-map parking-map-single" role="img" aria-label="${label} cerca de ${C.name}"><svg viewBox="0 0 900 560" xmlns="http://www.w3.org/2000/svg" aria-hidden="true"><rect width="900" height="560" fill="#edf1e9"/><g fill="#e3eadf" stroke="#d2dcd1" stroke-width="2"><path d="M0 0h210l25 145-205 35z"/><path d="M275 0h235l-18 155-198 20z"/><path d="M600 0h300v175l-275-30z"/><path d="M0 250l225-28 22 155-247 30z"/><path d="M310 205l190-20 15 170-205 20z"/><path d="M615 220l285-35v170l-260 30z"/><path d="M0 455l260-38 30 143H0z"/><path d="M380 410l205-28 20 178H350z"/><path d="M690 390l210-25v195H645z"/></g><g fill="none" stroke="#fff" stroke-linecap="round"><path stroke-width="46" d="M25 392 L875 345"/><path stroke-width="38" d="M250 -20 L360 590"/><path stroke-width="38" d="M590 -20 L520 590"/><path stroke-width="29" d="M35 120 L865 205"/><path stroke-width="27" d="M75 515 L845 480"/><path stroke-width="23" d="M40 270 L845 286"/><path stroke-width="22" d="M90 455 L815 420"/></g><g fill="none" stroke="#d1dad3" stroke-width="2"><path d="M25 392 L875 345"/><path d="M250 -20 L360 590"/><path d="M590 -20 L520 590"/><path d="M35 120 L865 205"/><path d="M75 515 L845 480"/><path d="M40 270 L845 286"/><path d="M90 455 L815 420"/></g><path d="${zonePath}" fill="rgba(44,147,98,.30)" stroke="#2c9362" stroke-width="7"/><g font-family="Inter,Arial" font-weight="900" fill="#17384d" paint-order="stroke" stroke="#fff" stroke-width="6" stroke-linejoin="round">${text}</g><g transform="translate(${homeX} ${homeY})"><circle r="36" fill="#06283f" stroke="#d8a43b" stroke-width="6"/><text text-anchor="middle" y="11" font-size="31" fill="#fff">⌂</text><rect x="-92" y="44" width="184" height="42" rx="16" fill="#06283f"/><text text-anchor="middle" y="72" font-family="Inter,Arial" font-size="18" font-weight="800" fill="#fff">${C.short} · ${t('youAreHere')||'ESTÁS AQUÍ'}</text></g><g transform="translate(42 42)"><circle r="25" fill="#fff" opacity=".96"/><path d="M0 -16 L7 4 L0 0 L-7 4Z" fill="#06283f"/><text x="0" y="42" text-anchor="middle" font-family="Inter" font-size="12" font-weight="900" fill="#06283f">N</text></g><g font-family="Inter,Arial" font-weight="900"><rect x="${variant===1?125:500}" y="${variant===1?205:300}" rx="18" width="230" height="55" fill="#fff"/><text x="${variant===1?150:525}" y="${variant===1?241:336}" font-size="22" fill="#24794f">${label.toUpperCase()}</text></g></svg></div><div class="street-chips">${streetList(items)}</div><a class="btn" target="_blank" rel="noopener" href="${n===1?C.parking.zone1:C.parking.zone2}">${t('navigate')}</a></article>`;
 };
 return layout(t('parkingTitle'),t('parkingLead'),`<div class="parking-zone-stack">${zoneMap(1,zone1Streets,1)}${zoneMap(2,zone2Streets,2)}</div><div class="grid two parking-options"><article class="card"><h3>🔵 ${t('ora')}</h3><p>${t('parkingTip')}</p><a class="btn outline" target="_blank" rel="noopener" href="https://www.telpark.com/es/">${t('telpark')}</a></article><article class="card"><h3>🟠 ${t('covered')}</h3><p>Parking Independencia · acceso por Camiño do Regueiro</p><a class="btn" target="_blank" rel="noopener" href="${C.parking.covered}">${t('navigate')}</a></article></div><p class="notice" style="margin-top:18px">💡 ${t('parkingTip')}</p>`,'SMART PARKING')
}
function restaurants(){let cuisineKeys=[...new Set(C.restaurants.map(r=>r.cuisine))];let filters=`<div class="filterbar"><button class="active" data-filter="all">${t('all')}</button>${cuisineKeys.map(c=>`<button data-filter="${c}">${t('cuisines.'+c)}</button>`).join('')}</div>`;let cards=C.restaurants.map(r=>`<article class="card restaurant-card" data-cuisine="${r.cuisine}"><div class="card-icon">${r.cuisine==='japanese'?'🍣':r.cuisine==='icecream'?'🍦':r.cuisine==='rice'?'🥘':'🍽️'}</div><h3>${r.name}</h3><div class="meta"><span class="pill">${t('cuisines.'+r.cuisine)}</span><span class="pill">${r.price}</span><span class="pill">${r.distance}</span></div><p>${t('notes.'+r.note)}</p><details><summary>${t('details')}</summary><p><b>${t('cuisine')}:</b> ${t('cuisines.'+r.cuisine)}</p><p><b>${t('price')}:</b> ${r.price}</p><p><b>${t('distance')}:</b> ${r.distance}</p><p><b>${t('specialties')}:</b> ${t('notes.'+r.note)}</p></details><div class="actions"><a class="btn" target="_blank" href="${r.route}">${t('navigate')}</a><a class="btn outline" target="_blank" href="${r.info}">${t('info')}</a></div></article>`).join('');return layout(t('restaurantsTitle'),t('restaurantsLead'),filters+`<div class="restaurant-grid" id="restaurantGrid">${cards}</div><p class="notice" style="margin-top:20px">ℹ️ ${lang==='es'?'Precios y tiempos orientativos. Confirma horarios y disponibilidad antes de salir.':'Guide prices and travel times. Confirm opening hours and availability before going.'}</p>`,'URBAN STAY FOOD')}
function discover(){let routes=beaches.map(x=>`<article class="card route-card"><div class="card-icon">${x.icon}</div><h3>${x.name}</h3><div class="route-meta"><span class="pill">${x.km} ${t('km')}</span><span class="pill">${x.time} ${t('minutes')} ${t('bycar')}</span></div><p>${routeTip(x.tip)}</p><a class="btn" target="_blank" href="https://www.google.com/maps/dir/?api=1&origin=${encodeURIComponent(C.address)}&destination=${encodeURIComponent(x.q)}">${t('navigate')}</a></article>`).join('');let cies=`<div class="banner" style="margin-top:22px"><span class="eyebrow">PARQUE NACIONAL</span><h2>${t('ciesTitle')}</h2><p>${t('ciesLead')}</p><div class="footer-actions"><a class="btn gold" target="_blank" href="https://autorizacionillasatlanticas.xunta.gal/illasr/inicio">${t('authorization')}</a><a class="btn" target="_blank" href="https://www.mardeons.es/">${t('tickets')}</a><a class="btn outline" target="_blank" href="https://www.google.com/maps/dir/?api=1&origin=${encodeURIComponent(C.address)}&destination=${encodeURIComponent('Estacion Maritima de Ria Vigo')}">${t('portRoute')}</a><a class="btn outline" target="_blank" href="https://illasatlanticas.gal/es/visita-el-parque/visita-cies">${t('parkInfo')}</a></div></div>`;return layout(t('beachesTitle'),t('beachesLead'),`<div class="grid three">${routes}</div>${cies}`,'VIGO · MAR Y VISTAS')}
function routeTip(k){let d={es:{family:'Playa amplia, paseo marítimo, servicios y ambiente familiar.',sand:'Arena clara y aguas tranquilas; muy agradable para pasar el día.',food:'Playa, puerto y restaurantes junto al mar.',sunset:'Mirador urbano ideal para pasear y ver el atardecer.',view:'Vistas abiertas de la ría y un paseo tranquilo.',walk:'Paseo marinero con terrazas y ambiente local.'},en:{family:'Large beach, promenade, services and a family atmosphere.',sand:'Light sand and usually calm water, ideal for a full beach day.',food:'Beach, harbour and seaside restaurants.',sunset:'Urban viewpoint, excellent for a walk and sunset.',view:'Open views over the estuary and a peaceful walk.',walk:'Seafront walk with terraces and local atmosphere.'}};return (d[lang]||d.en)[k]}
function eventsView(){
 let cards=events.map((e,i)=>`<article class="card event-card-live"><div class="event-date">${e.date}</div><div class="card-icon">${e.icon}</div><h3>${e.name}</h3><p>${e.place}</p><a class="btn" target="_blank" rel="noopener" href="${e.url}">${t('openOfficial')}</a></article>`).join('');
 return layout(t('eventsTitle'),t('eventsLead'),`<div class="grid three">${cards}</div><div class="banner" style="margin-top:22px"><h3>${t('fullAgenda')}</h3><p>${t('eventsLead')}</p><a class="btn gold" target="_blank" href="https://hoxe.vigo.org/?lang=cas">${t('fullAgenda')}</a></div>`,'VIGO EN VIVO')
}
function servicesView(){let names=serviceNames[lang]||serviceNames.en;let cards=services.map(([i,k,q])=>`<a class="card" target="_blank" href="${link(q)}"><div class="card-icon">${i}</div><h3>${names[k]}</h3><p>${t('searchNearby')}</p></a>`).join('');return layout(t('servicesTitle'),t('servicesLead'),`<div class="grid four service-grid">${cards}</div><div class="banner" style="margin-top:22px"><h3>🆘 ${t('emergency')}</h3><p>112 · Policía Nacional 091 · Policía Local 092</p></div>`,'TODO A MANO')}
function checkoutView(){return layout(t('checkoutTitle'),t('checkoutLead'),`<div class="grid three"><article class="card"><div class="card-icon">🕛</div><h3>${C.checkout}</h3><p>${t('checkout')}</p></article><article class="card"><div class="card-icon">✅</div><h3>${t('checkoutTitle')}</h3><p>${t('checkoutLead')}</p></article><article class="card"><div class="card-icon">⭐</div><h3>${t('review')}</h3><a class="btn gold" target="_blank" href="${C.review}">${t('review')}</a></article></div>`,'HASTA PRONTO')}
function render(){let r=(location.hash||'#home').slice(1);let f={home,homeinfo,parking,restaurants,discover,events:eventsView,services:servicesView,checkout:checkoutView}[r]||home;app.innerHTML=f();nav();document.querySelectorAll('[data-r]').forEach(a=>a.classList.toggle('active',a.dataset.r===r));drawer.classList.add('hidden');if(r==='restaurants')document.querySelectorAll('[data-filter]').forEach(b=>b.onclick=()=>{document.querySelectorAll('[data-filter]').forEach(x=>x.classList.remove('active'));b.classList.add('active');document.querySelectorAll('[data-cuisine]').forEach(c=>c.style.display=b.dataset.filter==='all'||c.dataset.cuisine===b.dataset.filter?'flex':'none')});window.scrollTo(0,0)}
brandLogo.src=footerLogo.src=C.logo;brandName.textContent=C.name;footerText.textContent=t('footer');languageSelect.value=lang;languageSelect.onchange=e=>{lang=e.target.value;localStorage.setItem('usg-lang',lang);document.documentElement.lang=lang;footerText.textContent=t('footer');render()};menuBtn.onclick=()=>drawer.classList.toggle('hidden');window.addEventListener('hashchange',render);render();
