const $=(s,p=document)=>p.querySelector(s), $$=(s,p=document)=>[...p.querySelectorAll(s)];
const DATA=window.Z89_DATA;
const I18N={
es:{welcomeSubtitle:'Tu guía personal para disfrutar Vigo.',enter:'Entrar',heroTitle:'Vive Vigo como alguien de aquí.',heroText:'Todo lo necesario para tu estancia, con recomendaciones personales, rutas y ayuda inteligente.',explore:'Explorar',askConcierge:'Preguntar al concierge',weatherNow:'Tiempo ahora',checkout:'Check-out',checkoutNote:'Salida tranquila',location:'Ubicación',openRoute:'Abrir ruta',occupancy:'Capacidad',guests:'huéspedes',stayEyebrow:'TU ESTANCIA',stayTitle:'Todo bajo control.',stayText:'Acceso rápido a la información que más necesitarás durante el viaje.',arrival:'Llegada',arrivalSub:'Portal y acceso',wifiSub:'QR y contraseña',apartment:'Apartamento',discover:'DESCUBRE VIGO',discoverTitle:'Elige lo que te apetece.',discoverText:'Filtra recomendaciones, consulta distancias y abre la ruta directamente.',interactiveMap:'Mapa interactivo',plans:'PLANES PERSONALIZADOS',plansTitle:'Un Vigo para cada viaje.',plansText:'Itinerarios listos para abrir y adaptar a tu ritmo.',useful:'INFORMACIÓN ÚTIL',usefulTitle:'Lo importante, siempre a mano.',pharmacy:'Farmacia abierta',searchNow:'Buscar ahora',parking:'Aparcamiento',seeOptions:'Ver opciones',routePort:'Ruta al puerto',hospital:'Hospital',yourHome:'TU CASA EN VIGO',homeText:'Amplio, luminoso y pensado para compartir sin renunciar a la privacidad.',rooms:'habitaciones',bathrooms:'baños',thanks:'GRACIAS POR TU ESTANCIA',reviewTitle:'Tu opinión nos ayuda a mejorar.',reviewText:'Comparte tu experiencia y ayuda a otros viajeros a descubrir Zamora 89.',reviewButton:'Valorar en Airbnb',install:'Instalar guía',conciergeSub:'Asistente local de la estancia',askPlaceholder:'Pregunta por desayunos, lluvia, parking…',aiNote:'Respuestas basadas en la guía local. Comprueba horarios y disponibilidad antes de salir.'},
en:{welcomeSubtitle:'Your personal guide to enjoy Vigo.',enter:'Enter',heroTitle:'Experience Vigo like a local.',heroText:'Everything you need for your stay, with personal recommendations, routes and smart help.',explore:'Explore',askConcierge:'Ask the concierge',weatherNow:'Weather now',checkout:'Check-out',checkoutNote:'Easy departure',location:'Location',openRoute:'Open route',occupancy:'Capacity',guests:'guests',stayEyebrow:'YOUR STAY',stayTitle:'Everything under control.',stayText:'Fast access to the information you will need most.',arrival:'Arrival',arrivalSub:'Entrance and access',wifiSub:'QR and password',apartment:'Apartment',discover:'DISCOVER VIGO',discoverTitle:'Choose what you feel like doing.',discoverText:'Filter recommendations, check distances and open directions.',interactiveMap:'Interactive map',plans:'PERSONALISED PLANS',plansTitle:'A Vigo for every trip.',plansText:'Ready-made itineraries you can adapt.',useful:'USEFUL INFORMATION',usefulTitle:'The essentials, always at hand.',pharmacy:'Open pharmacy',searchNow:'Search now',parking:'Parking',seeOptions:'See options',routePort:'Route to the port',hospital:'Hospital',yourHome:'YOUR HOME IN VIGO',homeText:'Spacious, bright and designed for sharing with privacy.',rooms:'rooms',bathrooms:'bathrooms',thanks:'THANK YOU FOR STAYING',reviewTitle:'Your opinion helps us improve.',reviewText:'Share your experience and help other travellers discover Zamora 89.',reviewButton:'Review on Airbnb',install:'Install guide',conciergeSub:'Local stay assistant',askPlaceholder:'Ask about breakfast, rain, parking…',aiNote:'Answers are based on the local guide. Check opening hours and availability before leaving.'},
fr:{enter:'Entrer',heroTitle:'Vivez Vigo comme un habitant.',explore:'Explorer',askConcierge:'Demander au concierge',weatherNow:'Météo actuelle',location:'Localisation',openRoute:'Ouvrir l’itinéraire',guests:'voyageurs',arrival:'Arrivée',apartment:'Appartement',discover:'DÉCOUVREZ VIGO',discoverTitle:'Choisissez selon vos envies.',interactiveMap:'Carte interactive',plans:'PROGRAMMES PERSONNALISÉS',useful:'INFORMATIONS UTILES',pharmacy:'Pharmacie ouverte',parking:'Parking',hospital:'Hôpital',rooms:'chambres',bathrooms:'salles de bain',reviewButton:'Évaluer sur Airbnb',install:'Installer le guide'},
pt:{enter:'Entrar',heroTitle:'Viva Vigo como um local.',explore:'Explorar',askConcierge:'Perguntar ao concierge',weatherNow:'Tempo agora',location:'Localização',openRoute:'Abrir rota',guests:'hóspedes',arrival:'Chegada',apartment:'Apartamento',discover:'DESCUBRA VIGO',discoverTitle:'Escolha o que lhe apetece.',interactiveMap:'Mapa interativo',plans:'PLANOS PERSONALIZADOS',useful:'INFORMAÇÃO ÚTIL',pharmacy:'Farmácia aberta',parking:'Estacionamento',hospital:'Hospital',rooms:'quartos',bathrooms:'casas de banho',reviewButton:'Avaliar no Airbnb',install:'Instalar guia'},
de:{enter:'Eintreten',heroTitle:'Erleben Sie Vigo wie ein Einheimischer.',explore:'Entdecken',askConcierge:'Concierge fragen',weatherNow:'Wetter jetzt',location:'Standort',openRoute:'Route öffnen',guests:'Gäste',arrival:'Ankunft',apartment:'Apartment',discover:'VIGO ENTDECKEN',discoverTitle:'Wählen Sie, worauf Sie Lust haben.',interactiveMap:'Interaktive Karte',plans:'PERSÖNLICHE PLÄNE',useful:'NÜTZLICHE INFORMATIONEN',pharmacy:'Geöffnete Apotheke',parking:'Parken',hospital:'Krankenhaus',rooms:'Zimmer',bathrooms:'Bäder',reviewButton:'Auf Airbnb bewerten',install:'Guide installieren'},
it:{enter:'Entra',heroTitle:'Vivi Vigo come una persona del posto.',explore:'Esplora',askConcierge:'Chiedi al concierge',weatherNow:'Meteo adesso',location:'Posizione',openRoute:'Apri percorso',guests:'ospiti',arrival:'Arrivo',apartment:'Appartamento',discover:'SCOPRI VIGO',discoverTitle:'Scegli ciò che ti va.',interactiveMap:'Mappa interattiva',plans:'PIANI PERSONALIZZATI',useful:'INFORMAZIONI UTILI',pharmacy:'Farmacia aperta',parking:'Parcheggio',hospital:'Ospedale',rooms:'camere',bathrooms:'bagni',reviewButton:'Recensisci su Airbnb',install:'Installa guida'}};
let lang=localStorage.getItem('z89-lang')||'es';
function t(k){return I18N[lang]?.[k]||I18N.es[k]||k}function applyLang(){document.documentElement.lang=lang;$('#languageSelect').value=lang;$$('[data-i18n]').forEach(el=>el.textContent=t(el.dataset.i18n));$$('[data-i18n-placeholder]').forEach(el=>el.placeholder=t(el.dataset.i18nPlaceholder));renderNav();renderCategories()}
const welcome=$('#welcome');$('#enterBtn').onclick=()=>{welcome.classList.add('is-hidden');sessionStorage.setItem('z89-entered','1')};if(sessionStorage.getItem('z89-entered'))welcome.classList.add('is-hidden');
function setMenu(open){$('#drawer').classList.toggle('is-open',open);$('#scrim').classList.toggle('is-visible',open);$('#drawer').setAttribute('aria-hidden',String(!open));$('#menuBtn').setAttribute('aria-expanded',String(open))}$('#menuBtn').onclick=()=>setMenu(true);$('#closeMenu').onclick=()=>setMenu(false);$('#scrim').onclick=()=>setMenu(false);
function renderNav(){const labels=lang==='en'?['Home','Your stay','Discover Vigo','Plans','Events','Useful info','Apartment','Review']:['Inicio','Tu estancia','Descubre Vigo','Planes','Fiestas y conciertos','Información útil','Apartamento','Valoración'];$('#drawerNav').innerHTML=['inicio','estancia','explorar','planes','agenda','util','galeria','valoracion'].map((id,i)=>`<a href="#${id}">${labels[i]}</a>`).join('');$$('#drawerNav a').forEach(a=>a.onclick=()=>setMenu(false))}
$('#languageSelect').onchange=e=>{lang=e.target.value;localStorage.setItem('z89-lang',lang);applyLang()};
const preferred=localStorage.getItem('z89-theme')||((matchMedia('(prefers-color-scheme:dark)').matches)?'dark':'light');document.documentElement.dataset.theme=preferred;$('#themeBtn').onclick=()=>{const n=document.documentElement.dataset.theme==='dark'?'light':'dark';document.documentElement.dataset.theme=n;localStorage.setItem('z89-theme',n)};
let active='all';function renderCategories(){const names=DATA.categories.map(c=>({id:c[0],label:lang==='en'?c[2]:c[1]}));$('#categoryFilters').innerHTML=names.map(c=>`<button class="${active===c.id?'is-active':''}" data-cat="${c.id}">${c.label}</button>`).join('');$$('#categoryFilters button').forEach(b=>b.onclick=()=>{active=b.dataset.cat;renderCategories();renderPlaces()})}
function mapsUrl(p){return `https://www.google.com/maps/dir/?api=1&origin=Calle+Zamora+89%2C+Vigo&destination=${p.q}`}
function priceLabel(price){const labels={'€':'Hasta 15 €','€€':'15–30 €','€€€':'30–50 €','€€€€':'Más de 50 €','Gratis':'Gratis'};return labels[price]||price}function renderPlaces(){const list=DATA.places.filter(p=>active==='all'||p.cat===active);$('#placeGrid').innerHTML=list.map(p=>`<article class="place-card" data-id="${p.id}" tabindex="0"><div class="place-card__top"><h3>${p.name}</h3><strong class="price-label">${p.price}<br><small>${priceLabel(p.price)}</small></strong></div><p>${p.desc}</p><div class="place-meta"><span>🚶 ${p.walk}</span><span>🚗 ${p.drive}</span></div></article>`).join('');$$('.place-card').forEach(card=>{const go=()=>selectPlace(card.dataset.id);card.onclick=go;card.onkeydown=e=>{if(e.key==='Enter')go()}})}
function selectPlace(id){const p=DATA.places.find(x=>x.id===id);if(!p)return;$('#mapLabel').textContent=p.name;$('#mapFrame').src=`https://www.openstreetmap.org/export/embed.html?bbox=${p.lon-.012}%2C${p.lat-.009}%2C${p.lon+.012}%2C${p.lat+.009}&layer=mapnik&marker=${p.lat}%2C${p.lon}`;$('#detailContent').innerHTML=`<span class="eyebrow">VIGO</span><h2>${p.name}</h2><p>${p.desc}</p><div class="place-meta"><span>🚶 ${p.walk}</span><span>🚗 ${p.drive}</span><span>${p.price} · ${priceLabel(p.price)}</span></div><a class="button" href="${mapsUrl(p)}" target="_blank" rel="noopener">${t('openRoute')}</a>`;openModal('detailModal')}

let eventFilter='all';
function renderEvents(){
 const list=DATA.events.filter(e=>eventFilter==='all'||e.type===eventFilter||(eventFilter==='Fiesta'&&e.type==='Fiesta tradicional'));
 $('#eventsGrid').innerHTML=list.map(e=>`<article class="event-card"><div class="event-card__date"><span>${e.date}</span><b>${e.type}</b></div><h3>${e.title}</h3><p>${e.text}</p><a href="${e.url}" target="_blank" rel="noopener">Ver información oficial →</a></article>`).join('');
 $$('.event-filters button').forEach(b=>{b.classList.toggle('is-active',b.dataset.eventFilter===eventFilter);b.onclick=()=>{eventFilter=b.dataset.eventFilter;renderEvents()}})
}

function renderPlans(){$('#planGrid').innerHTML=DATA.plans.map(p=>`<article class="plan-card"><span>${p.icon}</span><h3>${p.title}</h3><p>${p.text}</p><details><summary>Ver itinerario</summary><ol>${p.stops.map(s=>`<li>${s}</li>`).join('')}</ol></details></article>`).join('')}
function renderGallery(){$('#gallery').innerHTML=DATA.gallery.map((f,i)=>`<img loading="lazy" src="assets/${f}" alt="Zamora 89 Urban Stay ${i+1}">`).join('');$$('#gallery img').forEach(img=>img.onclick=()=>{$('#detailContent').innerHTML=`<img class="detail-photo" src="${img.src}" alt="${img.alt}">`;openModal('detailModal')})}
function openModal(id){const m=$('#'+id);m.classList.add('is-open');m.setAttribute('aria-hidden','false');document.body.style.overflow='hidden'}function closeModal(id){const m=$('#'+id);m.classList.remove('is-open');m.setAttribute('aria-hidden','true');document.body.style.overflow=''}$$('[data-close]').forEach(b=>b.onclick=()=>closeModal(b.dataset.close));$$('.modal').forEach(m=>m.onclick=e=>{if(e.target===m)closeModal(m.id)});document.addEventListener('keydown',e=>{if(e.key==='Escape')$$('.modal.is-open').forEach(m=>closeModal(m.id))});
const detail={arrival:`<span class="eyebrow">LLEGADA</span><h2>Así reconocerás Zamora 89</h2><img class="detail-photo" src="assets/portal-aprobado.png" alt="Portal"><p>La entrada está en el número 89 de la calle Zamora. El edificio dispone de puerta automática, rampa y ascensor.</p><a class="button" target="_blank" rel="noopener" href="https://www.google.com/maps/dir/?api=1&destination=Calle+Zamora+89%2C+Vigo">Abrir ruta</a>`,wifi:`<span class="eyebrow">WIFI</span><h2>Conexión del apartamento</h2><div class="wifi-box"><strong>MOVISTAR_1440</strong><code>PVkoGihBWPyYa8wAD6oy</code><img src="assets/wifi-qr-limpio.png" alt="QR WiFi"><button class="button" id="copyWifi">Copiar contraseña</button></div>`,home:`<span class="eyebrow">APARTAMENTO</span><h2>7 habitaciones · 4 baños</h2><img class="detail-photo" src="assets/kitchen.jpeg" alt="Cocina"><p>Cocina equipada, horno, microondas, lavadora, cafetera, comedor amplio, salón renovado y ascensor.</p>`,checkout:`<span class="eyebrow">CHECK-OUT · 12:00</span><h2>Antes de marcharte</h2><p>✓ Revisa que no olvidas nada.<br>✓ Apaga las luces y cierra las ventanas.<br>✓ Deja las llaves según las indicaciones recibidas.</p>`};$$('[data-open]').forEach(b=>b.onclick=()=>{$('#detailContent').innerHTML=detail[b.dataset.open];openModal('detailModal');$('#copyWifi')?.addEventListener('click',()=>navigator.clipboard.writeText('PVkoGihBWPyYa8wAD6oy').then(()=>toast('Contraseña copiada'))) });
function toast(msg){const el=$('#toast');el.textContent=msg;el.classList.add('is-visible');setTimeout(()=>el.classList.remove('is-visible'),2200)}
async function loadWeather(){try{const r=await fetch('https://api.open-meteo.com/v1/forecast?latitude=42.2406&longitude=-8.7207&current=temperature_2m,weather_code&timezone=Europe%2FMadrid');const j=await r.json();const c=j.current;$('#weatherTemp').textContent=Math.round(c.temperature_2m)+'°';const labels={0:'Despejado',1:'Poco nuboso',2:'Nubes',3:'Cubierto',45:'Niebla',51:'Llovizna',61:'Lluvia',63:'Lluvia',80:'Chubascos',95:'Tormenta'};$('#weatherText').textContent=labels[c.weather_code]||'Vigo';$('#weatherIcon').textContent=c.weather_code>=51?'☂':c.weather_code<=1?'☀':'☁'}catch(e){$('#weatherText').textContent='Vigo'}}
const responses=[
{keys:['desay','breakfast','café','cafe'],text:'Para desayunar, te recomiendo Mamá Elvira MARCO. También puedes consultar El Molino o Luces de Bohemia desde Google Maps.'},
{keys:['lluv','rain','pluie'],text:'Si llueve, una buena combinación es Museo do Mar, MARCO, café y una comida gallega. Tienes un itinerario “Vigo con lluvia” en la sección de planes.'},
{keys:['parking','aparc'],text:'Pulsa “Aparcamiento” en Información útil para ver los parkings disponibles cerca de Zamora 89 en ese momento.'},
{keys:['marisco','seafood'],text:'O Nisio es una de las recomendaciones destacadas para marisco. Comprueba el horario y reserva cuando sea posible.'},
{keys:['cíes','cies','islas'],text:'Para las Islas Cíes necesitas comprobar plazas y autorización. La guía abre la ruta desde Zamora 89 hasta la Estación Marítima.'},
{keys:['niñ','kids','children'],text:'Con niños: Playa de Samil, Museo do Mar y un helado en Capri. Puedes abrir el plan completo en “Plan con niños”.'},
{keys:['wifi','internet'],text:'Red: MOVISTAR_1440. La contraseña y el QR están en “Tu estancia → WiFi”.'},
{keys:['checkout','salida'],text:'El check-out es a las 12:00. Revisa pertenencias, apaga luces, cierra ventanas y deja las llaves según las indicaciones recibidas.'}
];
function addMessage(text,user=false){const d=document.createElement('div');d.className='message'+(user?' user':'');d.textContent=text;$('#chatMessages').appendChild(d);$('#chatMessages').scrollTop=$('#chatMessages').scrollHeight}function ask(q){addMessage(q,true);const low=q.toLowerCase();const found=responses.find(r=>r.keys.some(k=>low.includes(k)));setTimeout(()=>addMessage(found?found.text:'Puedo ayudarte con desayunos, lluvia, parking, marisco, Cíes, planes con niños, WiFi o check-out. Para horarios en tiempo real, abre la ruta de la recomendación.'),220)}
$('#openConcierge').onclick=()=>{openModal('conciergeModal');if(!$('#chatMessages').children.length)addMessage('¡Hola! Soy el concierge de Zamora 89. ¿Qué necesitas para disfrutar Vigo?')};$('#chatForm').onsubmit=e=>{e.preventDefault();const q=$('#chatInput').value.trim();if(q){ask(q);$('#chatInput').value=''}};const prompts=['¿Dónde desayuno?','¿Qué hago si llueve?','¿Dónde aparco?','Plan con niños'];$('#chatSuggestions').innerHTML=prompts.map(x=>`<button>${x}</button>`).join('');$$('#chatSuggestions button').forEach(b=>b.onclick=()=>ask(b.textContent));
$('#openAdmin').onclick=()=>{setMenu(false);openModal('adminModal')};$('#adminLogin').onclick=()=>{if($('#adminPin').value==='8989'){const c=JSON.parse(localStorage.getItem('z89-admin')||'{}');$('#adminArea').hidden=false;$('#adminWelcome').value=c.welcome||'';$('#adminReviewUrl').value=c.reviewUrl||'';$('#adminNotice').value=c.notice||''}else toast('PIN incorrecto')};$('#saveAdmin').onclick=()=>{const c={welcome:$('#adminWelcome').value,reviewUrl:$('#adminReviewUrl').value,notice:$('#adminNotice').value};localStorage.setItem('z89-admin',JSON.stringify(c));applyAdmin();toast('Cambios guardados')};$('#resetAdmin').onclick=()=>{localStorage.removeItem('z89-admin');location.reload()};$('#exportAdmin').onclick=()=>{const blob=new Blob([localStorage.getItem('z89-admin')||'{}'],{type:'application/json'});const a=document.createElement('a');a.href=URL.createObjectURL(blob);a.download='zamora89-config.json';a.click();URL.revokeObjectURL(a.href)};function applyAdmin(){const c=JSON.parse(localStorage.getItem('z89-admin')||'{}');if(c.welcome)$('[data-i18n="heroText"]').textContent=c.welcome;if(c.reviewUrl)$('#valoracion a').href=c.reviewUrl;if(c.notice){let n=$('#adminNoticeBanner');if(!n){n=document.createElement('div');n.id='adminNoticeBanner';n.className='toast is-visible';n.style.position='fixed';n.style.top='84px';n.style.bottom='auto';document.body.appendChild(n)}n.textContent=c.notice}}
let deferredPrompt;
const installBtn=$('#installBtn'),installAppBtn=$('#installAppBtn'),installBanner=$('#installBanner'),installHelp=$('#installHelp');
const isIos=/iphone|ipad|ipod/i.test(navigator.userAgent),isStandalone=matchMedia('(display-mode: standalone)').matches||navigator.standalone===true;
function showInstall(){if(isStandalone)return;if(installBtn)installBtn.hidden=false;if(installBanner&&!sessionStorage.getItem('z89-install-dismissed'))installBanner.hidden=false;if(isIos&&installHelp)installHelp.textContent='En iPhone: pulsa Compartir y después “Añadir a pantalla de inicio”.'}
async function installApp(){if(isStandalone){toast('La guía ya está instalada');return}if(deferredPrompt){deferredPrompt.prompt();await deferredPrompt.userChoice;deferredPrompt=null;if(installBanner)installBanner.hidden=true;return}if(isIos){toast('En iPhone: Compartir → Añadir a pantalla de inicio');return}toast('Abre el menú del navegador y elige “Instalar aplicación” o “Añadir a pantalla de inicio”')}
addEventListener('beforeinstallprompt',e=>{e.preventDefault();deferredPrompt=e;showInstall()});
if(installBtn)installBtn.onclick=installApp;if(installAppBtn)installAppBtn.onclick=installApp;
const closeInstall=$('#closeInstallBanner');if(closeInstall)closeInstall.onclick=()=>{installBanner.hidden=true;sessionStorage.setItem('z89-install-dismissed','1')};
addEventListener('appinstalled',()=>{if(installBanner)installBanner.hidden=true;toast('Guía instalada correctamente')});
if(!isStandalone)setTimeout(showInstall,900);
if('serviceWorker'in navigator)addEventListener('load',()=>navigator.serviceWorker.register('./sw.js?v=6.0'));
applyLang();renderPlaces();renderPlans();renderGallery();loadWeather();applyAdmin();
setInterval(()=>{const a=document.getElementById('weatherTemp'),b=document.getElementById('weatherTempBig');if(a&&b)b.textContent=a.textContent;},500);
